# docker-compose.yml
version: '3.8'
services:
  latex-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./bot/tmp:/usr/src/app/bot/tmp
    restart: always
